### ISSUE TITLE
Error when updating a PythonScript from file

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.PythonScripts#43] opened 2020-05-22 11:26 UTC
While investigating #42 I noticed the underlying problem surfaces at several spots.

When I try to update an already existing PythonScript instance from a file in Python 3, I get the following error:
```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 359, in publish_module
  Module ZPublisher.WSGIPublisher, line 262, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module Products.PythonScripts.PythonScript, line 200, in ZPythonScriptHTML_upload
  Module Products.PythonScripts.PythonScript, line 442, in write
TypeError: cannot use a string pattern on a bytes-like object
```

The code is currently without coverage.

**Comment by dataflake** [comment] 2020-05-22 11:40
This is just a duplicate of #42 with a different code path. Fix it in `write` to covr both cases. And do not blindly assume (like you do in #44) that you will always have an encoded string. Test for it first before decoding.

**Closed as completed** 2020-06-03 08:44 UTC
Labels: bug, duplicate
