### ISSUE TITLE
Error on Create new script from file

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Products.PythonScripts#42] opened 2020-05-21 08:29 UTC
When I create a new Python Script in the ZMI, there is the option of providing a text-file with the code. When I use this option I get an Internal Server Error:

    2020-05-21 10:26:17 ERROR [waitress:356][waitress] Exception while serving /websites/manage_addProduct/PythonScripts/manage_addPythonScript
    Traceback (most recent call last):
      File "/path/to/my/Zope/installation/lib/python3.8/site-packages/waitress/channel.py", line 349, in service
        task.service()
      File "/path/to/my/Zope/installation/lib/python3.8/site-packages/waitress/task.py", line 169, in service
        self.execute()
      File "/path/to/my/Zope/installation/lib/python3.8/site-packages/waitress/task.py", line 439, in execute
        app_iter = self.channel.server.application(environ, start_response)
      File "/path/to/my/Zope/installation/lib/python3.8/site-packages/ZPublisher/httpexceptions.py", line 30, in __call__
        return self.application(environ, start_response)
      File "/path/to/my/Zope/installation/lib/python3.8/site-packages/paste/translogger.py", line 69, in __call__
        return self.application(environ, replacement_start_response)
      File "/path/to/my/Zope/installation/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 359, in publish_module
        response = _publish(request, new_mod_info)
      File "/path/to/my/Zope/installation/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 254, in publish
        result = mapply(obj,
      File "/path/to/my/Zope/installation/lib/python3.8/site-packages/ZPublisher/mapply.py", line 85, in mapply
        return debug(object, args, context)
      File "/path/to/my/Zope/installation/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 63, in call_object
        return obj(*args)
      File "/path/to/my/Zope/installation/lib/python3.8/site-packages/Products/PythonScripts/PythonScript.py", line 97, in manage_addPythonScript
        pyscript.write(file)
      File "/path/to/my/Zope/installation/lib/python3.8/site-packages/Products/PythonScripts/PythonScript.py", line 441, in write
        m = _nonempty_line.search(text, st)
    TypeError: cannot use a string pattern on a bytes-like object

**Comment by georgpfolz** [comment] 2020-05-21 09:03
I get the same error when using myPythonScript.write(text) when text is bytes. If I decode "text" before the write operation, it works.

It's the same when I add a PythonScript programmatically:

    with open(filePath, 'rb') as ffiFile:
        ffiFile.seek(0)
        ffi = ffiFile.read()
        
        ffi = ffi.decode('utf-8') #  this is the part that makes it work
        REQUEST.form['file'] = ffi
        context.manage_addProduct['PythonScripts'].manage_addPythonScript(id='some_id', REQUEST=REQUEST)

By the way, it would be handy if the body of the script could be added as an argument instead of having to fake it into the REQUEST.

**Comment by jugmac00** [comment] 2020-05-22 07:35
I can confirm the bug with `Products.PythonScripts` 4.11 on Python 3.

Looks like nobody used that feature under Python 3 before. Also there is no coverage for that part in `manage_addPythonScript`.

The fix looks easy enough (iff `utf-8` is the only encoding we have to cover), test setup could take a bit.

@georgpfolz Want to try to fix the bug yourself? Please make sure to also add a test.

Concerning the feature request. I think it would be best to create a separate issue for that.

**Comment by jugmac00** [comment] 2020-05-22 08:36
Turns out - we use `Products.PythonScripts` in our company's app - and I have some spare time.

Jens already did the heavy lifting in creating test setup.

So I give it a try - PR incoming...

**Update**
As usual - it is a little bit more complicated... there are several callers of the `write` method, and currently they all pass in bytes instead of text. So, this will take a bit longer.

**Comment by dataflake** [comment] 2020-05-22 11:38
Why don't you just fix this inside `write` then..?

**Comment by jugmac00** [comment] 2020-05-22 12:30
Hi Jens,
I certainly put some thoughts where the problem should be fixed.

While fixing it at the `write`method, it obviously would mean only one place to change, but I am not convinced this is the correct spot.

Currently `write` has a very clear interface - it accepts text (even the parameter is called text) and it writes it. Easy enough. Let's make not more complicated.

Also, I usually like the "bytes at the boundary" principle which (simplified) says - convert str -> bytes and vice versa only at the boundaries, so you don't have to worry deeper down the stack - so no `if isinstance` checks.

While `write` is not declared private, it acts like one, as it is called several time by other methods (which reside at the outer boundary).

The third argument for keeping the fix out of `write` was that the other methods, ie `ZPythonScriptHTML_upload` already do the heavy lifting of checking the input, ie is it a str or a file, or whatever.

Also, did you notice, no `isinstance` check is necessary?

Only an omitted `if` is a good if :-D

Is my approach something we can talk about? At least I hope so!

**Comment by jugmac00** [comment] 2020-05-22 12:37
I did not recall where I read about this.. after some googling. It is Ned's fantastic article "Pragmatic Unicode" - https://nedbatchelder.com/text/unipain.html

Quote:
> Unicode sandwich: keep all text in your program as Unicode, and convert as close to the edges as possible.

**Comment by dataflake** [comment] 2020-05-22 12:49
`write` does not have "a very clear interface" just because the parameter is called `text`. The naming doesn't tell you anything in this case. All you can go by is what that method does to the input: Under both Python 2 and Python 3 it appears to treat the input as native string. It tries to find native strings in that input in several places or compare parts of it to native strings. So what you pass into it is actually different for Python 2 and Python 3. PR #44 does not account for that at all.

I personally value simpler solutions higher than trying to follow some theory.

**Comment by jugmac00** [comment] 2020-05-22 13:13
Personal values differ - no problem with that - and they also change over time.

I just had another look at the callers of write, and turns out you went with the same approach as I did (or try to do):
https://github.com/zopefoundation/Products.PythonScripts/blob/e4f9240f68ddcfaf680ae88fe874176cb6b1d294/src/Products/PythonScripts/PythonScript.py#L414-L425

So I guess both approaches are pretty ok?

I will write tests for all callers, so even if you or somebody else decides later on, that the `fix-in-write` method is the only correct solution, there will be a solid test suite, so refactoring will be easy.

Are you good with that?

**Comment by dataflake** [comment] 2020-05-22 13:16
Go ahead and fix the PR and I'll take a look

**Comment by georgpfolz** [comment] 2020-05-22 21:09
In DTMLMethod.py (OFS package) the "addDTMLMethod" method uses a function called "safe_file_data" which takes care of the data conversion. Maybe that would be a good idea for manage_addPythonScript as well. Here is the code:

    def safe_file_data(data):
        # Helper to convert upload file content into a safe value for saving
        if hasattr(data, 'read'):
            data = data.read()
        if PY3 and isinstance(data, binary_type):
            data = data.decode('utf-8')
        if PY2 and isinstance(data, text_type):
            data = data.encode('utf-8')
        return data

**Comment by jugmac00** [comment] 2020-06-03 07:18
Hi @georgpfolz 
I am currently on holiday, and afterwards a big pile of urgent work is waiting for me.

As the problem is located, at least one test is already written, one of the maintainers already pointed out where the fix should go, and you seem to have an idea also, what about give it a try and fix it yourself?

**Closed as completed** 2020-06-03 08:44 UTC
Labels: bug

**Comment by georgpfolz** [comment] 2020-06-03 09:09
@jugmac00 ok, I'll give it a try!

**Comment by dataflake** [comment] 2020-06-03 09:35
This is already fixed
